### ISSUE TITLE
Nothing shows up when clicking view HowLongToBeat data (again)

### ISSUE THREAD

**Issue by WerewolfNandah** [Lacro59/playnite-howlongtobeat-plugin#243]
**Describe the bug**
This issue was reported by Travers50 a few weeks ago. Now it's happening all over again.
I'm using his last post as a reference, since it's the same issue:
When pressing view HowLongToBeat datas to add the overlay onto my dashboard, no games show up. 

**To Reproduce**
Click any game, press 3 bars, hover over howlongtobeat, press view howlongtobeat datas, search, see nothing

**Expected behavior**
I expect to see a list of any games that could be related to the title of the entry you're searching for.

**Screenshots**
![HowLongToPlay Error](https://github.com/user-attachments/assets/ee136c8b-01b1-4dae-91e5-34a49c526184)

**Extensions log**
Attach Playnite's `Extensions.log` file. It is located in Playnite's installation directory in the portable version or in `%AppData%\Playnite` (Can be pasted in Explorer) in the installed version

**Comment by robbely** [comment]
It's either a coincidence and they're simply making changes to their website, or they are actively trying to break the plugin. Let's hope it's the former and that it can be fixed again.

**Comment by Aryanblood17** [comment]
yeah can confirm getting the same issue again

**Comment by samarthc** [comment]
Can confirm I have the same issue.

**Comment by Arrkayd** [comment]
Same issue here.

**Comment by Storbfall** [comment]
Same problem for any games.

**Comment by Sergiokool** [comment]
same anyone have the fix like the last time or it will be fixed?

**Comment by Maple-Elter** [comment]
Same here

**Comment by bivasbh** [comment]
Issue persisting after v3.6 update. The latest data being fetched is empty.

**Comment by Verssgn** [comment]
Could someone please upload one of their already setup games, the files are stored in ExtensionsData\e08cd51f-9c9a-4ee3-a094-fde03b55492f\HowLongToBeat I want to write a script that would allow you to manually add the HLTB data while this issue is getting fixed by the devs. (Don't have any game data since I reinstalled the addon). Thanks.

**Comment by wensleyoliv** [comment]
@Verssgn here's one.
[02887464-34d7-4485-a2f1-38987d9601ac.json](https://github.com/user-attachments/files/17963255/02887464-34d7-4485-a2f1-38987d9601ac.json)

**Comment by Verssgn** [comment]
> @Verssgn here's one. [02887464-34d7-4485-a2f1-38987d9601ac.json](https://github.com/user-attachments/files/17963255/02887464-34d7-4485-a2f1-38987d9601ac.json)

Thanks! If I get it to work I will post it here.

**Comment by Verssgn** [comment]
Here is a script that will allow you to download files for the addon from the HLTB website (This is a bandage solution), please note that the script sucks so for the button to appear refresh the website also give it couple of seconds to load - SCRIPT + TUTORIAL: https://greasyfork.org/en/scripts/519319-how-long-to-beat-to-playnite

**Please do not post issues with the script here!**

**Comment by robbely** [comment]
> ### How Long To Beat To Playnite Script
> 
> Here is a script that will allow you to download files for the addon from the HLTB website (This is a bandage solution while this issue is happening), please note that the script sucks so for the button to appear refresh the website also give it couple of seconds to load - SCRIPT + TUTORIAL: https://greasyfork.org/en/scripts/519319-how-long-to-beat-to-playnite
> 
> **Please do not post issues with the script here! Use the feedback section on greasyfork**

Works great, thank you :)

**Comment by Lacro59** [comment]
For information:
https://howlongtobeat.com/forum/thread/681/6#post118870

**Comment by bivasbh** [comment]
Works like a charm. Thanks

**Comment by johnnywnb** [comment]
Hi, I found the issue and submitted a fix via Pull Request.

While waiting for the official new release to be available, you can use this temporary release to test the fix on your side:
https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243

Just download and double-click on the .pext file while Playnite is open, or drag&drop the file into Playnite.

Hope it helps.

**Comment by PaulTheCarman** [comment]
> Hi, I found the issue and submitted a fix via Pull Request.
> 
> While waiting for the official new release to be available, you can use this temporary release to test the fix on your side: https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243
> 
> Just download and double-click on the .pext file while Playnite is open, or drag&drop the file into Playnite.
> 
> Hope it helps.

This fixed it for me. Thanks a ton. People like you are what make Playnite so great!

**Comment by Sergiokool** [comment]
> Hi, I found the issue and submitted a fix via Pull Request.
> 
> While waiting for the official new release to be available, you can use this temporary release to test the fix on your side: https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243
> 
> Just download and double-click on the .pext file while Playnite is open, or drag&drop the file into Playnite.
> 
> Hope it helps.

Ur truly a life saver mate, works like a charm, thanks a lot , hope Lacro could put you on his team of dev support :D

**Comment by WerewolfNandah** [comment]
> Hi, I found the issue and submitted a fix via Pull Request.
> 
> While waiting for the official new release to be available, you can use this temporary release to test the fix on your side: https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243
> 
> Just download and double-click on the .pext file while Playnite is open, or drag&drop the file into Playnite.
> 
> Hope it helps.

ACK I really want to thank you for this, but now my stupid antivirus tags it as a virus and auto-blocks it everytime I try to download it. How can I stop it from doing that?

**Comment by WerewolfNandah** [comment]
Great, I managed to download it from Firefox browser, but now my antivirus auto-tags the add-on itself as a virus and I can't load it anymore.
How can I fix that?

**Comment by johnnywnb** [comment]
> Great, I managed to download it from Firefox browser, but now my antivirus auto-tags the add-on itself as a virus and I can't load it anymore. How can I fix that?

Hi @WerewolfNandah , I don't know why your antivirus flagged this file as malicious. You could upload it to VirusTotal to scan it and check that it is totally safe.

Perhaps adding it as an exception in your antivirus could sort your issue.
If it does not work, you may decide to reinstall it from Playnite interface and wait for the next official release. That way, no manual installation will be required, so less risk of triggering any AV overzealous scans.

**Comment by WerewolfNandah** [comment]
I finally managed to install the fix and make the app work again.
Only two days later, though, the bug returns.

I'm just going to wait for an official fix up to this point, but I'm starting to lose my confidence to this app entirely. This is just ridiculously annoying.

**Comment by bryjo3** [comment]
This is broken again

**Comment by PaulTheCarman** [comment]
> I finally managed to install the fix and make the app work again. Only two days later, though, the bug returns.
> 
> I'm just going to wait for an official fix up to this point, but I'm starting to lose my confidence to this app entirely. This is just ridiculously annoying.

Broken for me as well. The HLTB extension has always had a history of only working half the time though lol. I don't think it's the dev's fault - I think HLTB just updates their website a lot. Verssgn's workaround still works for me though.

**Comment by WerewolfNandah** [comment]
> > I finally managed to install the fix and make the app work again. Only two days later, though, the bug returns.
> > I'm just going to wait for an official fix up to this point, but I'm starting to lose my confidence to this app entirely. This is just ridiculously annoying.
> 
> Broken for me as well. The HLTB extension has always had a history of only working half the time though lol. I don't think it's the dev's fault - I think HLTB just updates their website a lot. Verssgn's workaround still works for me though.

Yeah, I mean, I can tell this is clearly not the devs' intentions, and I bet they must be as pissed as we users. But it's just annoying to see this extension can't work on its own.
At least we've got that workaround, you're right about that.

**Comment by pedrosacca** [comment]
> I finally managed to install the fix and make the app work again. Only two days later, though, the bug returns.
> 
> I'm just going to wait for an official fix up to this point, but I'm starting to lose my confidence to this app entirely. This is just ridiculously annoying.

Same thing happened here. I was updating my library with two games, and while the plugin was downloading the information for both games simultaneously, one got the data, but the other failed to download anything. I retried for the other game with multiple different search words, but to no avail

**Comment by johnnywnb** [comment]
HLTB has changed the default value of the parameter they recently added.
I updated the Pull Request branch to reflect the change.

Here is the compiled extension with the updated fix:
https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243-2

**Comment by WerewolfNandah** [comment]
> > I finally managed to install the fix and make the app work again. Only two days later, though, the bug returns.
> > I'm just going to wait for an official fix up to this point, but I'm starting to lose my confidence to this app entirely. This is just ridiculously annoying.
> 
> Same thing happened here. I was updating my library with two games, and while the plugin was downloading the information for both games simultaneously, one got the data, but the other failed to download anything. I retried for the other game with multiple different search words, but to no avail

It works again! 
Thank you so much!

**Comment by PaulTheCarman** [comment]
> HLTB has changed the default value of the parameter they recently added. I updated the Pull Request branch to reflect the change.
> 
> Here is the compiled extension with the updated fix: https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243-2

Once again, you are an absolute goat. Thank you man, mad respect. 🫡

**Comment by Thiagojustino1** [comment]
> HLTB has changed the default value of the parameter they recently added. I updated the Pull Request branch to reflect the change.
> 
> Here is the compiled extension with the updated fix: https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243-2

Thank you very much! This worked for me.

**Comment by K1LL3RPUNCH** [comment]
Yeah, same here :p

**Comment by bivasbh** [comment]
Working great now. Thanks a ton.

**Comment by FeyrisTan** [comment]
Does this still work? I had to (sadly) switch from arch kde to windows because kde HDR does not work for me. So I went back to playnite and tried this fix. Data still does not show up. Did something change again?

**Comment by WerewolfNandah** [comment]
> Does this still work? I had to (sadly) switch from arch kde to windows because kde HDR does not work for me. So I went back to playnite and tried this fix. Data still does not show up. Did something change again?

Yes, it has...
It's not working once again. Damnit.

**Comment by johnnywnb** [comment]
HLTB has decided to change their Search API parameters again. 
I updated the Pull Request branch to reflect the latest change.

Here is the compiled extension with the updated fix:
https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243-3

**Comment by WerewolfNandah** [comment]
> HLTB has decided to change their Search API parameters again. I updated the Pull Request branch to reflect the latest change.
> 
> Here is the compiled extension with the updated fix: https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6-hotfix%23243-3

Well, I'm afraid they've probably changed something _again_, because the issue still persists after the hotfix.

You're our hero, bud, taking your time and effort to keep fixing something that stubbornly insists on breaking itself again.

**Comment by bivasbh** [comment]
Yes, the bug is back again. I'm so sorry. You guys fixed it, and again, they changed something... 😢

**Comment by Verssgn** [comment]
The new update has fixed the issue for me, thanks!

**Comment by bivasbh** [comment]
@johnnywnb Thanks a lot. I downloaded it and it works really well. Thank you @Lacro59 and @johnnywnb for all the hard work.

**Comment by WerewolfNandah** [comment]
Oh yes! It works like a charm now. Thanks a lot again!!

**Comment by WerewolfNandah** [comment]
I hate to be that guy again, but the issue has returned...

**Comment by JDOGGOKUSSJ2** [comment]
yeah its messed up again

**Comment by johnnywnb** [comment]
HTLB has changed their api endpoint again. I've submitted a Pull Request for @Lacro59 to have a look at.

In the meantime, here is a hotfix release I compiled while waiting for the official release. Feel free to use it to test the fix on your side:
https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6.1-hotfix-search

**Comment by robbely** [comment]
> HTLB has changed their api endpoint again. I've submitted a Pull Request for @Lacro59 to have a look at.
> 
> In the meantime, here is a hotfix release I compiled while waiting for the official release. Feel free to use it to test the fix on your side: https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.6.1-hotfix-search

Tested and works thank you. However the latest official version is 3.7.0 - so playnite wants to update to a broken one again. Maybe change the version number to 3.7.1?

**Comment by johnnywnb** [comment]
@robbely thanks! 
I've updated the release to use version 3.7.0 indeed:

https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.7.0-hotfix-search

Lacro will decide on the next version name (3.7.1 or 3.8). In the meantime, it's best to keep this hotfix release version similar to the current one so that when the new official release gets available, Playnite picks it up naturally.

**Comment by atakanvg** [comment]
Again its broken

**Comment by weslleyvieira-dev** [comment]
Broken again
